### ISSUE TITLE
Android Fatal Exception SDLThread

### ISSUE THREAD

**Issue by PXshadow** [openfl/lime#1178]
OpenFl 8.0
Lime 6.3.0
hxcpp git
haxe 4.0 preview 3 

Application will build just fine but when it launches it'll crash as a black screen before render of stage.

Here is the output:
```
05-06 02:08:02.363 20217 20238 E AndroidRuntime: FATAL EXCEPTION: SDLThread
05-06 02:08:02.363 20217 20238 E AndroidRuntime: Process: com.ThinQbatorApp, PID: 20217
05-06 02:08:02.363 20217 20238 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for int org.libsdl.app.SDLActivity.nativeInit(java.lang.Object) (tried Java_org_libsdl_app_SDLActivity_nativeInit and Java_org_libsdl_app_SDLActivity_nativeInit__Ljava_lang_Object_2)
05-06 02:08:02.363 20217 20238 E AndroidRuntime: 	at org.libsdl.app.SDLActivity.nativeInit(Native Method)
05-06 02:08:02.363 20217 20238 E AndroidRuntime: 	at org.libsdl.app.SDLMain.run(SDLActivity.java:1092)
05-06 02:08:02.363 20217 20238 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
```

**Comment by PXshadow** [comment]
Issue was on my end because template files were changed from previous version.
