### ISSUE TITLE
`lime build emscripten` fails

### ISSUE THREAD

**Issue by JesseTG** [openfl/lime#727]
Running `lime build emscripten` fails with the following Python stack trace:

```
emcc -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DEMSCRIPTEN -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -Wno-warn-absolute-paths -DSTATIC_LINK -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -I/usr/share/haxelib/hxcpp/3,2,205/include -x c++ -frtti --std=c++11 -Wno-invalid-offsetof -Wno-return-type-c-linkage ./src/openfl/ui/GameInputControl.cpp -o /home/jesse/Common/Code/Similar-Game/export/emscripten/obj/obj/emscripten-stat/93c331ae_GameInputControl.o
emcc -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DEMSCRIPTEN -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -Wno-warn-absolute-paths -DSTATIC_LINK -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -I/usr/share/haxelib/hxcpp/3,2,205/include -x c++ -frtti --std=c++11 -Wno-invalid-offsetof -Wno-return-type-c-linkage ./src/openfl/utils/_Object/Object_Impl_.cpp -o /home/jesse/Common/Code/Similar-Game/export/emscripten/obj/obj/emscripten-stat/17373ae1_Object_Impl_.o
emcc -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DEMSCRIPTEN -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -Wno-warn-absolute-paths -DSTATIC_LINK -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -I/usr/share/haxelib/hxcpp/3,2,205/include -x c++ -frtti --std=c++11 -Wno-invalid-offsetof -Wno-return-type-c-linkage ./src/openfl/text/TextLineMetrics.cpp -o /home/jesse/Common/Code/Similar-Game/export/emscripten/obj/obj/emscripten-stat/22f45667_TextLineMetrics.o
emcc -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DEMSCRIPTEN -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -Wno-warn-absolute-paths -DSTATIC_LINK -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -I/usr/share/haxelib/hxcpp/3,2,205/include -x c++ -frtti --std=c++11 -Wno-invalid-offsetof -Wno-return-type-c-linkage ./src/openfl/ui/GameInputDevice.cpp -o /home/jesse/Common/Code/Similar-Game/export/emscripten/obj/obj/emscripten-stat/93c331ae_GameInputDevice.o
Error: error: Unknown attribute kind (45)
Traceback (most recent call last):
  File "/usr/bin/emcc", line 1504, in <module>
    shared.Building.llvm_opt(temp_file, llvm_opts)
  File "/usr/share/emscripten/tools/shared.py", line 1357, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
```

That last line is not a typo, the `output` variable is empty.

Doing so with the `-debug` flag doesn't fare much better.  The log looks like this:

```
# Lots of similar-looking emcc invocations...
emcc -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H -c -fvisibility=hidden -g -fpic -fPIC -DEMSCRIPTEN -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -Wno-warn-absolute-paths -DHXCPP_DEBUG -DSTATIC_LINK -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -I/usr/share/haxelib/hxcpp/3,2,205/include -x c++ -frtti --std=c++11 -Wno-invalid-offsetof -Wno-return-type-c-linkage /usr/share/haxelib/hxcpp/3,2,205/src/hx/Lib.cpp -o /home/jesse/Common/Code/Similar-Game/export/emscripten/obj/obj/emscripten-stat-debug/4d5ce5da_Lib.o
Error: /usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:315:9: error: unknown type name 'HxAtomicLock'
typedef HxAtomicLock ThreadPoolLock;
        ^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:975:18: warning: array index 1 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(1)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:33: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                ^           ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:358:1: note: array 'sThreadWake' declared here
ThreadPoolSignal sThreadWake[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:975:18: warning: array index 1 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(1)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:50: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                                 ^               ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:357:1: note: array 'sThreadSleeping' declared here
bool             sThreadSleeping[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:976:18: warning: array index 2 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(2)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:33: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                ^           ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:358:1: note: array 'sThreadWake' declared here
ThreadPoolSignal sThreadWake[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:976:18: warning: array index 2 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(2)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:50: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                                 ^               ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:357:1: note: array 'sThreadSleeping' declared here
bool             sThreadSleeping[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:977:18: warning: array index 3 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(3)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:33: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                ^           ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:358:1: note: array 'sThreadWake' declared here
ThreadPoolSignal sThreadWake[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:977:18: warning: array index 3 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(3)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:50: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                                 ^               ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:357:1: note: array 'sThreadSleeping' declared here
bool             sThreadSleeping[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:978:18: warning: array index 4 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(4)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:33: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                ^           ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:358:1: note: array 'sThreadWake' declared here
ThreadPoolSignal sThreadWake[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:978:18: warning: array index 4 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(4)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:50: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                                 ^               ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:357:1: note: array 'sThreadSleeping' declared here
bool             sThreadSleeping[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:979:18: warning: array index 5 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(5)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:33: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                ^           ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:358:1: note: array 'sThreadWake' declared here
ThreadPoolSignal sThreadWake[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:979:18: warning: array index 5 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(5)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:50: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                                 ^               ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:357:1: note: array 'sThreadSleeping' declared here
bool             sThreadSleeping[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:980:18: warning: array index 6 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(6)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:33: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                ^           ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:358:1: note: array 'sThreadWake' declared here
ThreadPoolSignal sThreadWake[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:980:18: warning: array index 6 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(6)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:50: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                                 ^               ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:357:1: note: array 'sThreadSleeping' declared here
bool             sThreadSleeping[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:981:18: warning: array index 7 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(7)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:33: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                ^           ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:358:1: note: array 'sThreadWake' declared here
ThreadPoolSignal sThreadWake[MAX_MARK_THREADS];
^
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:981:18: warning: array index 7 is past the end of the array (which contains 1 element) [-Warray-bounds]
            else CHECK_THREAD_WAKE(7)
                 ^                 ~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:971:50: note: expanded from macro 'CHECK_THREAD_WAKE'
               SignalThreadPool(sThreadWake[tid],sThreadSleeping[tid]); \
                                                 ^               ~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:357:1: note: array 'sThreadSleeping' declared here
bool             sThreadSleeping[MAX_MARK_THREADS];
^
In file included from /usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:4:
/usr/share/haxelib/hxcpp/3,2,205/include/hx/Thread.h:183:59: error: member reference base type 'int' is not a structure or union
   TAutoLock(LOCKABLE &inMutex) : mMutex(inMutex) { mMutex.Lock(); }
                                                    ~~~~~~^~~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:962:29: note: in instantiation of member function 'TAutoLock<int>::TAutoLock' requested here
         ThreadPoolAutoLock l(sThreadPoolLock);
                            ^
In file included from /usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:4:
/usr/share/haxelib/hxcpp/3,2,205/include/hx/Thread.h:184:25: error: member reference base type 'int' is not a structure or union
   ~TAutoLock() { mMutex.Unlock(); }
                  ~~~~~~^~~~~~~
/usr/share/haxelib/hxcpp/3,2,205/src/hx/gc/Immix.cpp:962:29: note: in instantiation of member function 'TAutoLock<int>::~TAutoLock' requested here
         ThreadPoolAutoLock l(sThreadPoolLock);
                            ^
14 warnings and 3 errors generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
```

`clang --version` returns this:

```
clang version 3.8.1-svn268518-1~exp1 (branches/release_38)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

And I'm running Kubuntu 15.10.

However, I have several versions of LLVM installed, with the version managed through `update-alternatives` (though admittedly it may not be set up properly or completely).

**Comment by jgranick** [comment]
I have not tested Emscripten support in a while, compilation of the Lime binary should still work, but if there are other issues like these, it is probably caused by needed updates to the HXCPP library for better Emscripten support. If you are interested, try the latest HXCPP, and see if it performs better?

When last tested, OpenFL HTML5 output compiles much faster, is smaller and runs much better than Emscripten, but this could change in the future. I would love to hear what you find, and would be happy to assist more on Slack or the forums if you dig into this.

I apologize for the long delay in adding a comment here :smile:
